Create SHT41 Sensor Driver
CarletonURocketry/fetcher pull request #17
Opened 2024-02-28 00:19 UTC by AngusJull

- Added a driver for the SHT41 sensor that fits the sensor interface
- Added functions for calculating an 8-bit cyclic redundancy check
- Added needed code in main to set up fetching of temperature and humidity data

Resolves #10

2024-02-28 14:12 UTC, linguini1 requested changes

2024-02-28 14:12 UTC, linguini1 commented on src/main.c
> +    sensor_set_ctx(&sensors[2], sysclock_context);
Here you should be setting the context to `sht41_context` instead of `sysclock_context`.

2024-02-28 14:12 UTC, linguini1 commented on src/sensors/sensor_api.c
> +        {.name = "Humidity", .unit = "%RH", .fmt_str = "%.0f", .dsize = sizeof(float), .dtype = TYPE_FLOAT},
Since this is a float, it would be ideal (in my opinion) to use `%.2f` so we can get at least two decimals. Is there a reason (due to accuracy or otherwise) that this is 0 decimal places?

2024-02-28 14:12 UTC, linguini1 commented on src/sensors/sensor_api.h
> +    TAG_HUMIDITY,    /**< Humidity in % relative humitidy */
Very picky but small typo in docstring for "humidity".

2024-02-28 14:12 UTC, linguini1 commented on src/sensors/sht41/sht41.c
> +static const uint16_t MEAUREMENT_TIMES[] = {
Little typo on `MEASUREMENT_TIMES`

2024-02-28 14:12 UTC, linguini1 commented on src/sensors/sht41/sht41.h
> +#define SHT41_USE_CRC_LOOKUP
Since you have conditional compilation, I would exclude this from the header file. Then it becomes up to the user of the library to define it if they want that feature.

```c
/* Somewhere in main.c */
#include "sensors/ms5611/ms5611.h"
#define SHT41_USE_CRC_LOOKUP
#include "sensors/sht41/sht41.h"
#include "sensors/sysclock/sysclock.h"
```

2024-02-28 14:16 UTC, linguini1 commented
Some minor review comments before I merge, but this looks really clean. I don't know much about CRC so thank you for your implementation. Good idea to use conditional compilation.

What's the difference between the two CRC checks (lookup table vs polynomial)? And the hard-coded lookup table would apply to more than just the SHT41?

2024-02-29 02:15 UTC, AngusJull commented on src/sensors/sensor_api.c
> +        {.name = "Humidity", .unit = "%RH", .fmt_str = "%.0f", .dsize = sizeof(float), .dtype = TYPE_FLOAT},
I worry that adding more decimals would deceive people as to what our sensor's accuracy is, which at the very best is +/-1.0% but, with our sensor and at the temperatures we operate at, should be over +/-2%.

2024-02-29 02:26 UTC, linguini1 commented on src/sensors/sensor_api.c
> +        {.name = "Humidity", .unit = "%RH", .fmt_str = "%.0f", .dsize = sizeof(float), .dtype = TYPE_FLOAT},
> I worry that adding more decimals would deceive people as to what our sensor's accuracy is, which at the very best is +/-1.0% but, with our sensor and at the temperatures we operate at, should be over +/-2%.

Fair point, I didn't realize that was the accuracy. Could you then please change the data type to an unsigned integer of 8 bits? That will be enough to store 0-100 and is better than having a float without using the precision.

Alternatively, you could use a float for the humidity tag but have the `sht41_read` function round to the nearest whole number every time and allow the humidity format string to be `%.2f`

2024-02-29 02:29 UTC, AngusJull commented on src/sensors/sht41/sht41.h
> +#define SHT41_USE_CRC_LOOKUP
Sure, haven't thought of putting a define in the main file. It does make my clangd think that it isn't defined and greys out a bunch of stuff, which is a little sad

2024-02-29 02:33 UTC, linguini1 submitted a review, later dismissed

2024-02-29 02:35 UTC, linguini1 commented
I'm approving this, but if you could at some point change the humidity to be .2f of precision when printed and just round the values internally in `sht41_read()` that would be ideal.

Great work and nice job doing it so quickly! I'll let you hit the merge button.

2024-02-29 02:39 UTC, AngusJull commented
> Some minor review comments before I merge, but this looks really clean. I don't know much about CRC so thank you for your implementation. Good idea to use conditional compilation.
> 
> What's the difference between the two CRC checks (lookup table vs polynomial)? And the hard-coded lookup table would apply to more than just the SHT41?

A quick way of describing CRCs is that you take the input data in bytes, then divide it using a polynomial. The remainder is a CRC and can be used for detecting errors in the transmission of the data - basically, we could tell if I2C was having problems. Doing a CRC like you would by hand, you do a bunch of bit shifts and XORs for every byte - but since the division of a byte by a certain polynomial is always the same, you may as well just store it in a lookup table and save yourself the hassle.

Most people choose to give up some memory for much faster CRC calculation using a table. The lookup table is applicable to any CRC-8 calculation, so long as it uses the same polynomial, which isn't a certainty.

2024-02-29 03:02 UTC, AngusJull commented
Sorry for the push notifications, I should probably not be doing so much revision of the commits themselves.

Last time I force push on this one - promise :)

2024-02-29 13:06 UTC, linguini1 approved these changes
Looks great!

2024-02-29 13:06 UTC, merged