M10spg
CarletonURocketry/fetcher pull request #22
Opened 2024-03-12 23:25 UTC by matt-bekkers

Adds m10spg functionality (hopefully)

2024-03-12 23:29 UTC, matt-bekkers commented
I beg to holier powers that this may work, and if it does not I will rewrite the entire thing in NMEA format as pennance

2024-03-16 14:53 UTC, linguini1 requested changes

2024-03-16 14:53 UTC, linguini1 commented on src/main.c
> +#include "sensors/m10spg/include/m10spg.h"
Remove the include subdir and just keep `.c` and `.h` files in the same `sensors/m10spg/` folder.

2024-03-16 14:53 UTC, linguini1 commented on src/main.c
> +    sensor_set_ctx(&sensors[2], m10spg_context);
Make sure you're keeping the sensor number consistent. You're using `sensors[3]` and `sensors[2]` which will give you bugs. Should be 3.

2024-03-16 14:53 UTC, linguini1 commented on src/sensors/m10spg/m10spg.c
> +#define DCMD_I2C_SENDRECV __DIOTF(_DCMD_I2C, 7, i2c_sendrecv_t)
This should not be needed. What did you add it to accomplish?

2024-03-16 14:53 UTC, linguini1 commented on src/sensors/m10spg/m10spg.c
> +uint8_t gps_address = 0x42;
Might be okay for debugging but I'd set this in `main.c` where you'll be running from.

2024-03-16 18:00 UTC, matt-bekkers commented on src/main.c
> +    sensor_set_ctx(&sensors[2], m10spg_context);
fixed

2024-03-16 18:01 UTC, matt-bekkers commented on src/sensors/m10spg/m10spg.c
> +#define DCMD_I2C_SENDRECV __DIOTF(_DCMD_I2C, 7, i2c_sendrecv_t)
thought I would need it for I2C and forgot to take it out, sorry

2024-03-26 02:26 UTC, linguini1 commented on src/sensors/m10spg/m10spg.c
> +    uint8_t read_cmd[sizeof(header) + 2];
If possible I'd try to make these two things static (saves stack memory), and just change the `.slave` field between calls. This is picky but it's only because I have been very heavy-handed with using the stack elsewhere and want to save a little lol.

2024-03-26 02:26 UTC, linguini1 commented on src/sensors/m10spg/m10spg.c
> + * @param result The total number of bytes ready to be read
Also picky but maybe pick something like `bytes_in_buffer` instead of `result`?

2024-03-26 02:27 UTC, linguini1 reviewed
Change looks great! Glad you got it working! Only reason this isn't an approval review is because if I approve this it can be merged and I know it's not ready yet

2024-03-26 02:34 UTC, AngusJull commented
Not working yet! I was using this command to try and get a better sense of what was going on today and thought I should keep it.

2024-03-26 03:07 UTC, linguini1 commented
> Not working yet! I was using this command to try and get a better sense of what was going on today and thought I should keep it.

UBLOX hates to see us winning

2024-05-21 03:47 UTC, AngusJull commented on src/sensors/m10spg/m10spg.c
> +    uint8_t read_cmd[sizeof(header) + 2];
Made a bunch of these into static variables

2024-05-21 03:51 UTC, AngusJull commented
Resolves #8. 

We'll need new issues for all the improvements that can be made to this work. I also expect we might need to talk about the data types again. Converting altitude to a float could be more agnostic of the sensor, but would hurt our performance on smaller processors for not much gain. I would prefer just to use mm and a unsigned integer, and maybe we can just be more careful about our math for the MS5611 and change that too. This also works better for the packager format, since it uses unsigned integers for GPS data. 

I think there's a decent amount of duplication the collector that could be fixed too.

2024-05-22 00:14 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +// [UBX_MON_VER] = {.header = {.class = 0x0A, .id = 0x04, .length = 0x00}, .checksum_a = 0x0E, .checksum_b = 0x34},
I'd just include this in the array now anyways, it's useful to have

2024-05-22 00:17 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +    static i2c_send_t write_header = {.stop = 0, .len = 1};
When I added `static` previously, I was actually mistaken. It may save stack space, but whenever we have two of the same sensor on one board, there may be data corruption with these static variables being shared between threads. Even though it's unlikely we'll have 2 GPSs on the same board, I'd remove the `static` unless the variable is read-only (in that case add `const`) to keep our libraries thread safe.

2024-05-22 00:19 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +    uint8_t read_cmd[sizeof(header) + nbytes];
I know UBX headers are quite long; might want to force the caller to add the extra `sizeof(header)` (probably 20) bytes to their `void *buf` instead of re-allocating that space on the function call stack. Fine for now but it puts a lot of stuff on the stack.

2024-05-22 00:19 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +    } while ((stop.tv_sec - start.tv_sec) < timeout);
This scares me but it's definitely the M10's fault lol.

2024-05-22 00:20 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +    add_valset_item(&msg, (uint32_t)0x10720002, &config_disabled, UBX_TYPE_L);
I'd probably `#define` these hex values.

2024-05-22 00:23 UTC, linguini1 commented on src/drivers/m10spg/m10spg.c
> +// DEBUG FUNCTIONS
I'd surround this in a `#ifndef __M10_DEBUG__` or something, along with the `#include <stdio.h>` to reduce overhead on final builds. But that's picky

2024-05-22 00:26 UTC, linguini1 commented on src/drivers/sensor_api.h
> +    TAG_LATITUDE = 9,         /**< Latitude in units of 0.1 microdegrees */
Latitude and longitude will be bundled together, but this is okay for now.

2024-05-22 00:26 UTC, merged

2024-05-22 00:27 UTC, linguini1 commented
Merging for now, added some review comments to work on while implementing more features though.

2024-06-02 01:30 UTC, AngusJull commented on src/drivers/m10spg/m10spg.c
> +    } while ((stop.tv_sec - start.tv_sec) < timeout);
yuup. I think going to a periodic model would be better for this reason, we shouldn't need to wait for our response